-- SQL Migration: "Open to all countries" sentinel for remote job postings
-- Execute this SQL script in your Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql)
--
-- A remote job that is open to every country is stored as a single
-- `job_locations` row with country_id = -1.
--
-- `job_locations.country_id` carries a foreign key to `countries(id)`, and every
-- read path embeds it (`countries:country_id(name)`), so -1 has to be a real row
-- rather than a magic number outside the table. This seeds that row:
--
--   * id         = -1        the sentinel the application writes and reads
--   * name       = Worldwide what job cards, the detail page and the JobPosting
--                            structured data render for such a listing
--   * is_active  = false     /api/geo?type=countries only returns active rows, so
--                            the sentinel never appears in a country picker
--
-- `countries.id` is GENERATED ALWAYS AS IDENTITY, so the explicit id needs
-- OVERRIDING SYSTEM VALUE. The block below checks the catalog first so the
-- migration also runs against a schema where `id` is a plain/serial column.

DO $$
DECLARE
    v_identity char;
BEGIN
    IF EXISTS (SELECT 1 FROM public.countries WHERE id = -1) THEN
        RAISE NOTICE 'Worldwide sentinel (id = -1) already present, nothing to do.';
        RETURN;
    END IF;

    SELECT attidentity INTO v_identity
    FROM pg_attribute
    WHERE attrelid = 'public.countries'::regclass
      AND attname = 'id'
      AND NOT attisdropped;

    IF v_identity = 'a' THEN
        -- GENERATED ALWAYS AS IDENTITY
        INSERT INTO public.countries (id, name, code, is_active)
        OVERRIDING SYSTEM VALUE
        VALUES (-1, 'Worldwide', 'WW', false);
    ELSE
        -- GENERATED BY DEFAULT AS IDENTITY, serial, or a plain bigint
        INSERT INTO public.countries (id, name, code, is_active)
        VALUES (-1, 'Worldwide', 'WW', false);
    END IF;

    RAISE NOTICE 'Worldwide sentinel (id = -1) created.';
END $$;

-- The sentinel must never be reachable through the state/city hierarchy: a
-- worldwide row is country-only, with state_province_id and city_id left NULL.
ALTER TABLE public.job_locations
    DROP CONSTRAINT IF EXISTS job_locations_worldwide_has_no_subdivision;

ALTER TABLE public.job_locations
    ADD CONSTRAINT job_locations_worldwide_has_no_subdivision
    CHECK (
        country_id <> -1
        OR (state_province_id IS NULL AND city_id IS NULL)
    );

-- The country filter unions the selected countries with the sentinel on every
-- job search, so this index is on the hot path.
CREATE INDEX IF NOT EXISTS idx_job_locations_country_id
    ON public.job_locations (country_id);

-- Verify
SELECT id, name, code, is_active FROM public.countries WHERE id = -1;
